### ISSUE TITLE
consider running under puma instead of passenger

### ISSUE THREAD

**Issue by starsplatter** [cul-it/exhibits-library-cornell-edu#100]
Things are really slow when it's doing background jobs. Would running under puma be faster?

**Comment by cappadona** [comment]
Not sure...are you noticing a hit with as little as one background job? Any specific examples we can try to reproduce and benchmark?

**Comment by starsplatter** [comment]
This was based on doing the bulk upload. I'm not sure if it kicks off one job or two, because it has to both index the items and generate their derivatives. It runs much faster on my local machine with puma than on the dev box with passenger. 

What would benchmarking look like? I have the spread and we can reingest it into a new exhibit if that's helpful.

**Comment by cappadona** [comment]
Thanks. For initial numbers, you can try using the [Chrome Devtools network panel](https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#requests) running the same bulk upload in:

1. Local instance on puma
1. Dev VM on passenger

**Comment by cappadona** [comment]
Jenn ran a large import today on production and was happy with performance. Marking this as wontfix for now.
