### ISSUE TITLE
Add Matomo

### ISSUE THREAD

**Issue by mhk33** [cul-it/exhibits-library-cornell-edu#101]

**Comment by mhk33** [comment]
@elrayle This is something we never got around to doing. Would you be able to add something like the Matomo gem so that we can begin collecting stats?
https://github.com/matomo-org/piwik-ruby-api

**Comment by elrayle** [comment]
Looks like Matomo is an alternative to Google Analytics.  More info at their website.  https://matomo.org/

NOTE: Google Analytics is already set up for exhibits.

**Comment by elrayle** [comment]
Fixed by PR #384 - add analytics dashboard
