### ISSUE TITLE
Saved searches not populating in search results widget

### ISSUE THREAD

**Issue by ker87** [cul-it/exhibits-library-cornell-edu#107]
I'm trying to use search results widgets to display images on feature pages.  I made several of them, now saved searches that I have made recently are not populating in the widget "Add a title" field; older saved searches are populating.  Newer saved searches are appearing in the drop down for "Select a title to update a previously saved search" when saving a search.

One of the searches I am currently trying to use is based on the Attribution field, the other is based on exhibit tags.  For replication purposes, the titles of the searches involved are "benito" and "lesser".

**Comment by starsplatter** [comment]
Hi -

It looks like in order for the categories to be available to the menu they need to be marked published in the interface. After I checked "Benito test", it became available (you'll see i added it to the benito page). Screenshot attached of what I mean.
![screen shot 2017-06-19 at 1 18 01 pm 2](https://user-images.githubusercontent.com/2148239/27297203-faaa3140-54f1-11e7-8b18-114dbb11150b.png)

**Comment by starsplatter** [comment]
Let me know if that solves the problem for you @ker87

**Comment by ker87** [comment]
That appears to fix it.  Was there a prior behavior where that became checked by default?  I do not believe I checked my prior saved searches.

**Comment by starsplatter** [comment]
I don't think so. The others have thumbnails saved to them so maybe in that process they got the checkmark? I'm not sure. I'll close this issue for now but just let us know if anything else crops up.

**Comment by ker87** [comment]
Roger that.
