### ISSUE TITLE
Masonry display of search blocks image clickthrough

### ISSUE THREAD

**Issue by ker87** [cul-it/exhibits-library-cornell-edu#116]
Having an issue with masonry view of a search.  See this page (https://exhibits.library.cornell.edu/vintage-vision/feature/george-lepape) and its related search.

Masonry view through the display search widget is making a mouseover that gives the full metadata of the image that covers the entire image, making it impossible to click the image to go to the full entry for it.

![masonry view issue](https://user-images.githubusercontent.com/28395147/27543795-3b3c94a2-5a59-11e7-9edf-9e67e22ca1f2.jpg)

This persists with all metadata types unchecked for masonry on the metadata dashboard page.  It stops displaying the full metadata on mouseover if list or gallery display types are also selected in the widget (not slideshow), but will not display masonry as the default choice for display even with that selected as the default display for the search.

I am hoping to have the behavior be to display the masonry view with title only in the mouseover without having additional display types (or at least with masonry as the default when the page is first displayed).

**Comment by cappadona** [comment]
@starsplatter My understanding is that Masonry should be using the title as the default caption, but I don't see `title` as an option under metadata. Any idea what might be going on here?

**Comment by starsplatter** [comment]
@cappadona title doesn't appear under metadata i think because it is a default you can't turn off. not showing it all is probably not the best UI to represent that.

For the masonry issue this appears to be a browser compatibility problem? I do not see the bad behavior in Chrome, only Firefox.

**Comment by ker87** [comment]
I was getting the issue in Chrome.

**Comment by starsplatter** [comment]
interesting. it is okay in my chrome but not firefox. okay, we'll work on tracking it down. 
<img width="1280" alt="screen shot 2017-06-26 at 11 47 51 am" src="https://user-images.githubusercontent.com/2148239/27547935-68db483e-5a65-11e7-8fd8-7988975ccfda.png">

**Comment by cappadona** [comment]
@starsplatter Thanks. Not working for me in Chrome `Version 59.0.3071.109`

**Comment by mhk33** [comment]
It doesn't work for me either in Chrome. I see the full metadata on top of the image and can't click on it.

**Comment by starsplatter** [comment]
Okay, we think we have the problem nailed down so we can work on it. In the meantime, @ker87 if you go to your main search results and toggle it to masonry:

https://exhibits.library.cornell.edu/vintage-vision/catalog?q=&search_field=all_fields&utf8=%E2%9C%93&view=masonry

And THEN go to your feature page, the masonry view should look ok. We will fix though!

**Comment by ker87** [comment]
Tried this workaround and it's persisting for me in both Firefox and Chrome.

**Comment by ker87** [comment]
Workaround functions after discussing with Nick.  Interestingly, all instances of masonry displays are showing proper functionality after performing one new search (not just those associated with the new search).

**Comment by ker87** [comment]
Issue has returned.  Left it alone for a few days, logged in just now and it's happening again (it had been working from this computer using this browser (Firefox) prior to the holiday).

**Comment by cappadona** [comment]
Thanks for the update, @ker87. Just wondering...are you able to toggle it back? This is just a temporary workaround as we attempt to address the underlying issue. I plan on circling back to this before the end of the week.

**Comment by ker87** [comment]
Yes, it toggled back.

**Comment by cappadona** [comment]
Thanks for confirming.

**Comment by cappadona** [comment]
Related to projectblacklight/spotlight#1802

**Comment by starsplatter** [comment]
Hi @ker87 this should be fixed now!

**Comment by cappadona** [comment]
Thanks @starsplatter!
