### ISSUE TITLE
Nightly Solr replication (aka backup)

### ISSUE THREAD

**Issue by cappadona** [cul-it/exhibits-library-cornell-edu#121]
See #98 for more details.

**Comment by elrayle** [comment]
@gdelisle Do we have nightly backups?  If so, you can close this issue.

**Comment by JesiBuell79** [comment]
How is this being backed-up?

**Comment by gdelisle** [comment]
It is not being backed up. The machine itself is getting backed up via a snapshot of its drives, but that's not really a good way to do it. This solr should be backed up via a Jenkins job that I can create, and I'll do that.

**Comment by gdelisle** [comment]
Link to LibSys Jira ticket: https://culibrary.atlassian.net/browse/DLITSYS-4945

**Comment by gdelisle** [comment]
The backup job is running now, from this Jenkins job: https://awsjenkins.library.cornell.edu/job/exhibits-solr-backup-production/ It backs up using Solr's built-in replication and it stores backups locally in /cul/backup/solr. Beyond that, the machine is backed up nightly as an AMI (machine image). This is in place only for production, exhibits-integration-solr is not backed up.
