### ISSUE TITLE
Create form for describing non-Spotlight exhibits so they can be displayed

### ISSUE THREAD

**Issue by starsplatter** [cul-it/exhibits-library-cornell-edu#135]
I met with communications today. Their advice for taming the exhibit backlog and getting some pointers to legacy exhibits in the interface is to ask for help from ME. To do so, I think we would create a Drupal form on the main library site that allows ME's staff to enter

Exhibit Title
Exhibit Thumbnail
Exhibit Description 
Exhibit URL

We'd then harvest or export these to turn them into the cards that populate the exhibits home page.

If we can beef up the content on exhibits.library.cornell.edu, communications endorses getting rid of this page: https://www.library.cornell.edu/about/collections/online-exhibitions

Thoughts?

**Comment by mhk33** [comment]
This sounds good to me, Jenn. I guess the form on the main site would be behind authentication? Or you could only access it if you are a user on the site? Just wondering about keeping it out of public display.

**Comment by starsplatter** [comment]
yes behind web auth sounds good!

**Comment by starsplatter** [comment]
do you want to take this for the form? i can do the export/import after

**Comment by mhk33** [comment]
Sure! is there a timeframe?

**Comment by starsplatter** [comment]
sooner-ish? i think communications wants to avoid drawing too much attention to the domain until it has more content.

**Comment by mhk33** [comment]
OK, I can try to work on it soon.
I was also wondering if it's possible to get this info from a Localist feed?

**Comment by starsplatter** [comment]
Maybe i'm forgetting -isn't localist events? This is for stuff that's old and I'm not sure if localist would have what we need? But maybe there is more in localist than i realize.

**Comment by mhk33** [comment]
This feed appears to have some exhibits, but I'm not sure how far back it goes and if they are tagged in a consistent way:
http://events.cornell.edu/calendar?event_types%5B%5D=4205
We can totally go with the form if that's easiest! Just thought I'd mention it.

**Comment by mhk33** [comment]
@starsplatter  Is this all that you need for Michelle?:
https://www.library.cornell.edu/exhibits-form
It is behind CUWebAuth, but I haven't linked it to anything, or anything.

**Comment by starsplatter** [comment]
looks perfect. i added myself to receive emails and updated the submission behavior to not redirect to a new page so its easier to add a bunch in a row. i added one just using what seemed obvious from the rmc pages. i think the biggest concern is the thumbnails. if we can't use the small ones rmc has new ones will have to get made? https://rare.library.cornell.edu/exhibitions/online are small. there are larger thumbnails inside but then we are looking at selection  http://rmc.library.cornell.edu/godsandscholars/exhibition/objects/index.html

**Comment by mhk33** [comment]
Cool - let me know if you need anything else from me!
