### ISSUE TITLE
Union-Made exhibit has multiple occurrences of the Sir Trevor bug

### ISSUE THREAD

**Issue by cappadona** [cul-it/exhibits-library-cornell-edu#141]
As originally reported by Rachel.

> See #88 and projectblacklight/spotlight#1782 for more details on the bug

**Comment by starsplatter** [comment]
thank you for doing this!

**Comment by mhk33** [comment]
@cappadona @starsplatter Sorry to bug you guys about spotlight... Kheel is running into an error when clicking on Browse categories here:
https://exhibits.library.cornell.edu/go-figure/browse
I'm wondering if this is the bug reported in this issue. I'm not sure how to tell if it is, but if so, would eihter of you be able to provide me with more info for how to fix?
(Side note: we are still lacking a developer with more chops than I, on this site. :)

**Comment by cappadona** [comment]
Hey @mhk33. I believe this ties back to the same underlying bug (an empty object for the block data) based on a quick review of the production log.

We actually have this documented in Box (in the Spotlight directory), as mentioned here in #122, but it took me a while to track that down even though I remembered it was there. Sorry about that.

Let me know if you need a hand.

**Comment by mhk33** [comment]
Thanks @cappadona — I just saw the note about documentation on that other issue. I'll check it out and let you know if I need help. I'm thinking this is the same bug, anyway.

**Comment by chrisrlc** [comment]
Looks like this was fixed with a previous spotlight upgrade.
