### ISSUE TITLE
Enable facets

### ISSUE THREAD

**Issue by mhk33** [cul-it/exhibits-library-cornell-edu#146]
Per Slack conversation, it looks like you can't see the facet config through the browser admin UI. Jenn says she thinks it needs to be enabled in the catalog controller.

**Comment by starsplatter** [comment]
So to do this we need to know the name of the facet that she wants because they have to be added individually to the catalog controller.

**Comment by mhk33** [comment]
Can we add Date and Attribution for now, to show them what it will look like? (And then talk with them about the controlled vocabulary.)

**Comment by starsplatter** [comment]
I can do that but will it take some work because the basic metadata fields are not set up to be indexed as facets. Also, enabling the basic metadata fields as facets on one project will enable them on any exhibit using facets.

**Comment by JesiBuell79** [comment]
@mhk33 was there ever any movement on this to your knowledge?

**Comment by mhk33** [comment]
I think we can close this, I don't recall this being a problem any time recently.
