### ISSUE TITLE
Not authorized to access page message appears when uploading masthead

### ISSUE THREAD

**Issue by mhk33** [cul-it/exhibits-library-cornell-edu#154]
Patrizia reports that when she tried to upload a small image for the masthead in the Union Made exhibit, she got a message saying she was not authorized to access the page.

She has been editing the exhibit and is listed as an admin. I was able to upload the masthead for her, but wanted to record this bug, even though I have not reproduced it.

**Comment by mhk33** [comment]
Maybe related to this:
https://github.com/projectblacklight/spotlight/issues/1752

**Comment by mhk33** [comment]
Rachel is recently ran into this, too.

**Comment by elrayle** [comment]
Fixed by PR #283
