### ISSUE TITLE
Feature page widget disappears when you edit a page

### ISSUE THREAD

**Issue by mhk33** [cul-it/exhibits-library-cornell-edu#157]
Kheel reported this for the Union-Made home page. I tested it out by adding the widget with 4 feature pages. Only 3 appeared (maybe due to the sidebar on the home page). Then when you edit the page, the widget appears, but it is empty (feature pages are no longer listed).

I also tested it on the Jenn Test exhibit to see if it was only happening on Union-Made, but it happened there as well.

**Comment by mhk33** [comment]
This happened again for Kelsie on the Texture exhibit. I tested it out and it happened for me as well.

To reproduce:

* add a Pages widget to the home page
* save the home page
* you will see the Pages display properly
* edit the home page
* you will see the Pages widget is there, but pages are no longer appearing in the widget (it is empty)
* leave or save the page (without edits) and the Pages widget will no longer display

**Comment by elrayle** [comment]
Fixed by PR #379 which fixed the same issue described in Issue #374.
