### ISSUE TITLE
User is unable to upload images

### ISSUE THREAD

**Issue by mhk33** [cul-it/exhibits-library-cornell-edu#163]
Rachel gets the "we're sorry, something went wrong" screen when she tries to do a manual upload to Union Made.

I tested it out with the images that were not working for her, but the uploaded worked fine.

I'm not sure if this is related to Patrizia's issue (#154) where she couldn't upload/save a masthead. In that case, she get a permissions alert on the page.

**Comment by elrayle** [comment]
We do not have a way to test whether or not this is still a problem.  #154 is fixed, so hopefully, the fix for that fixed this too.
