### ISSUE TITLE
Unable to edit page title

### ISSUE THREAD

**Issue by mhk33** [cul-it/exhibits-library-cornell-edu#166]
Rachel from Costume/Kheel is unable to edit the page title on this page:
https://exhibits.library.cornell.edu/biggest-little-fashion-city/feature/the-biggest-little-fashion-city

She says she gets an error when she tries to save it, though she's able to make other changes on the page without a problem.

I don't get an error when saving it.

**Comment by elrayle** [comment]
Closing... Unable to reproduce.
