### ISSUE TITLE
create .env.example

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#177]
I was not able to find the file .env.example that is referenced in the README.

**Comment by cappadona** [comment]
@elrayle Looks like [it was deleted](https://github.com/cul-it/exhibits-library-cornell-edu/pull/160/files#diff-cbfd64a28982a1818f2b5f16e7f9d634) as part of #160.

**Comment by elrayle** [comment]
Fixed by #327
