### ISSUE TITLE
Cannot remove tag from item?

### ISSUE THREAD

**Issue by cappadona** [cul-it/exhibits-library-cornell-edu#22]
Maybe I'm just not seeing where to do this, but I mistakenly added the "Slum Clearance Maps" tag to this item:
http://exhibits-dev.library.cornell.edu/spotlight/land-use/catalog/2-25

I don't see a way to remove it. I do see where you can delete the whole tag, but I don't want to do that!
> _Imported from Jira_
> https://issues.library.cornell.edu/browse/SPOT-29

**Comment by mhk33** [comment]
I thought @starsplatter figured out how to do this, but I'm still not seeing a way to remove a tag from an item.
http://exhibits-dev.library.cornell.edu/spotlight/test-exhibit/catalog/3-57

**Comment by starsplatter** [comment]
I think this is a css or js problem.

**Comment by chrisrlc** [comment]
Seems to work now. Can reopen if still an issue.
