### ISSUE TITLE
Small thumbnails are sized up in div

### ISSUE THREAD

**Issue by cappadona** [cul-it/exhibits-library-cornell-edu#24]
http://exhibits-dev.library.cornell.edu/spotlight/land-use/feature/transit-maps
> _Imported from Jira_
> https://issues.library.cornell.edu/browse/SPOT-31

**Comment by mhk33** [comment]
This still appears to happen with Item Embed and Item Row. The image same image didn't upsample when using Upload Item Row:
http://exhibits-dev.library.cornell.edu/spotlight/test-exhibit/feature/history-of-the-collection
I don't know how much of a use case we have for using such small images, though (e.g. if this is worth fixing).

**Comment by cappadona** [comment]
Icebox for now. Add something to documentation about recommendation for minimum image size. #25

**Comment by mhk33** [comment]
This is added to the documentation under Curation > Items > Minimum image size:
https://cul-it.github.io/exhibits-library-cornell-edu/
