### ISSUE TITLE
Consider suppressing IIIF viewer of image is under a certain size?

### ISSUE THREAD

**Issue by cappadona** [cul-it/exhibits-library-cornell-edu#28]
Like in portal.

Example image, which can only be shown as a thumbnail (not sure how many of these there will be in the future, though):
http://exhibits-dev.library.cornell.edu/spotlight/land-use/catalog/2-21
> _Imported from Jira_
> https://issues.library.cornell.edu/browse/SPOT-32

**Comment by mhk33** [comment]
We are not suppressing the viewer in the portal, and I'm not sure that image size is as much of an issue in Spotlight, so I am going to close this. Also there is another issue for Spotlight upsampling thumbnail-size images.
