### ISSUE TITLE
Create tag set for top-level exhibits

### ISSUE THREAD

**Issue by mhk33** [cul-it/exhibits-library-cornell-edu#307]
Right now the top-level tags are a bit all over the place. I suggested this tag set, which Lynette shared with users for feedback:

* Agriculture & Food
* Arts & Humanities
* Home Economics & Design
* Science & Nature
* Society & Politics

**Comment by mhk33** [comment]
Denise suggests the following tags instead:

* Arts & Design
* Humanities & Social Science
* Industry & Labor
* Science & Nature
* Health & Home Economics
* Politics & Economics

Also a comment from Denise about tagging based on specific collections:

"I think tagging collections might be nice - that’s what I was commenting on, that the Costume Collection is now the Cornell Fashion + Textile Collection. In those earlier tags you have listed Kheel, Mann, so it might be nice to have these broader categories for tags, but also a way to see all of the exhibits from a specific collection or collaboration between collections."

**Comment by mhk33** [comment]
From Eveline:

"1.       Home Economics & Design – suggest changing to Fashion and Design; “home economics” is such a historically bound concept, it seems a little off-base to make it a lead exhibit category; the exhibits we (Mann) have relating to home ec would probably fall under “Fashion and Design” and/or “Society & Politics”—so those exhibits would certainly find a home.
2.       Or if we do want “Home Economics” in there as a category (I realize Eileen Keating may weigh in with a strong preference there!), I suggest putting it in its own category.
3.       That said, we might consider adding a “Cornelliana” category as well at some point—for exhibits that hold a significant amount of content that engages with  Cornell and/or its historical figures."

**Comment by mhk33** [comment]
From Susette:

"We've had a brief side conversation about potential topics as well. In the art world, "Design" is a pretty loaded term--to me it falls under Arts and Humanities, while others might first think of Industrial design or Landscape Design. But looking at the exhibits currently categorized there, it might refer to Fashion & Textiles?

One other category that might be useful could include engineering and forms of industry that live outside science and also includes all the great labor topics--maybe call it Industry & Labor?"

**Comment by elrayle** [comment]
Controlled list of tags was added in PR #367 add official set of exhibit tags.

```
    ["Arts and Design",
      "Food and Agriculture",
      "Gender and Sexuality",
      "Humanities and Social Science",
      "Industry and Labor",
      "Science and Technology",
      "Cornelliana"]
```

@mhk33 If these are correct, can you close this issue.  If not, list what they should be.

**Comment by elrayle** [comment]
In use in the production system.
