### ISSUE TITLE
debug logger permissions set to 666 instead of 664

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#330]
## Description

Debug logger causes runtime error unless all 3 levels have rw permissions.  The possible users that could have been trying to write to the log should have been one of ec2-user, webapp, or root.  They are all in the group, i.e. in the /etc/group file.

The permissions are set using `.ebextensions/sidekiq_permissions.config`.  For debug, the permissions are set to 0666, but would prefer to have them set to 0664.

## Expected

When permissions for `log/debug.log` are set to `0664`, the application should be able to write to that file.

## Actual

When permissions for `log/debug.log` are set to `0664`, the application gets permission error when trying to write to that file.

NOTE: With permissions set to `0666`, the app will not get the permissions error.

## To Reproduce

* create a branch with `.ebextensions/sidekiq_permissions.config` setting the permissions of $DEBUG_LOG to `chmod 0666 $DEBUG_LOG`
* deploy that branch to exhibits-int
* ssh into AWS machine for exhibits-int
* run rails console (this will try to write to the debug logger)
```
cd /var/app/current
bundle exec rails c
```

With permissions set to `0664`, rails console will produce a permissions error for file `log/debug.log`.

**Comment by chrisrlc** [comment]
Closing because of planned infrastructure changes that will be making this obsolete.
