### ISSUE TITLE
Spotlight forget password link doesn't include domain name

### ISSUE THREAD

**Issue by cappadona** [cul-it/exhibits-library-cornell-edu#34]
The change my password link points to localhost:3000. Same for accept invitation email.
> _Imported from Jira_
> https://issues.library.cornell.edu/browse/SPOT-6

**Comment by mhk33** [comment]
https://github.com/cul-it/exhibits-library-cornell-edu/blob/master/config/application.rb#L11

**Comment by mhk33** [comment]
I ended up making this change:
https://github.com/cul-it/exhibits-library-cornell-edu/commit/95f9490537728c1bc0d1eb13d6d12e5214adcdc1

Do we want to be able to distinguish between the prod and dev domains? Right now this is working on dev, but the "Change my password" link in the email takes you to prod.

**Comment by starsplatter** [comment]
I think should probably pull in the host name from the environment.

Also changing the from address didn't seem to take. It looks like it needs to get changed in devise.

![screen shot 2017-05-22 at 12 39 33 pm 2](https://cloud.githubusercontent.com/assets/2148239/26319141/c66b651e-3eeb-11e7-9e14-71ee488d23de.png)

**Comment by mhk33** [comment]
Yes, I still needed to change the address. Not sure if that was part of this issue, there's another one for customizing this email message so it's not so spammy.

I'll see if I can get it to pull the host name based on environment.

**Comment by mhk33** [comment]
This is working now in prod -- the "Change password" link in the email goes to exhibits.library.cornell.edu. But I think in Slack we talked about setting it up so that the domain will also point to exhibits-dev if you forget password from exhibits-dev.

**Comment by cappadona** [comment]
Thanks @mhk33. I remember that now. My vote is to [add an environment variable](https://github.com/cul-it/exhibits-library-cornell-edu/blob/dev/.env.example).

**Comment by mhk33** [comment]
@cappadona @starsplatter what email address do we want to send these system notifications from? libraryux@cornell.edu? dcaps@cornell.edu? other?

**Comment by cappadona** [comment]
@mhk33 I don't have a strong opinion since I'm not subscribed to either one ;)

**Comment by chrisrlc** [comment]
Looks like this was already done with the EMAIL_URL env variable.
