### ISSUE TITLE
Reverse default order of exhibits

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#421]
### Description

By default, display the most recently published exhibit as the first exhibit on the site home page.

### Current behavior

Newly published exhibits are placed at the end of the list on the site home page.

#### Curatorial Considerations

We do not have a point person responsible for the curation of the Exhibits site as a whole.  It is not clear who would approve a request that impacts all exhibits.

#### Technical Considerations

This also requires a technical exploration to determine the complexity of this change.  We are currently using the default behavior of Spotlight.  Also, exhibits can be manually reordered by site admins.  I do not know what impact it would have on this manual ordering when a new exhibit is shifted into the first position in the list.

**Comment by chrisrlc** [comment]
This came up again as a request in the latest stakeholder meeting. A preliminary investigation shows that this is maybe less straightforward than I would have expected...

Looks like [we sort currently by exhibit "weight"](https://github.com/projectblacklight/spotlight/blob/v3.3.0/app/controllers/spotlight/exhibits_controller.rb#L14), but everything created after 2019 has a weight of 50?? We could theoretically change sorting to published_at desc for published exhibits, but this column doesn't seem to be populated??

`select id, title, weight, published, published_at, created_at from spotlight_exhibits;`

Some open questions:

- How is spotlight_exhibits.weight supposed to be determined?
- Why is spotlight_exhibits.published_at null for published exhibits?
- Less important: How should unpublished exhibits be sorted?

**Comment by chrisrlc** [comment]
Related to https://github.com/cul-it/exhibits-library-cornell-edu/issues/483
