### ISSUE TITLE
Accessibility: "i" tag used to format text - Icons

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/exhibits-library-cornell-edu#437]
**Description**
Icons that are brought in typically use the `<i>` tag as a default. This is present on all pages of the site with the collapsed menu for mobile.

**Solutions**
Change `<i class="fa fa-bars">` to `<span class="fa fa-bars">` in the header so that the icon is no longer using the "i" tag.

**Comment by mhk33** [comment]
We don't appear to be using the <i> tag any more for the navbar-toggle. I don't see any other uses of <i> for icons in the views.

However, I do still see this coming up as an issue for italic text, as spotlight is using <i>...</i> rather than <em>...</em> for italics within Sir Trevor.
