### ISSUE TITLE
Is Sir Trevor _heading_block override still needed?

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#453]
### Description

Spotlight passes headers through a markdown parser.  This allows characters normally interpreted as html (e.g. `<`, `>`, `<p>`, `</p>`, etc) to appear in headers as they are typed.  

Spotlight: `Hello <p>World</p>` produces header with text `Hello <p>World</p>`

Override: `Hello <p>World</p>` produces header with text `Hello &lt;p&gt;World&lt;/p&gt;`

I'm not sure we have the use case of having html show up in a heading `Hello <p>World</p>`, so it is fine to keep the override if the original, which uses the parser, causes problems.

### Related Work

Override added in PR #1 - fix heading block

Parser added in  https://github.com/projectblacklight/spotlight/pull/953 to resolve #https://github.com/projectblacklight/spotlight/issues/944

**Comment by chrisrlc** [comment]
This override was removed when we did the spotlight upgrade.
