### ISSUE TITLE
Browse with masonry shows title and metadata over the image when hovering

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#468]
### Description

When a page includes the Browse widget with the default display set to Masonry, it displays title and metadata in the 3.x site and just title in current production.  

### Current Production

When hovering over a Browse image in the current production site, only the title is displayed in a small bar spanning the width of the image.

Example: Vintage Vision -> Artists -> [George Barbier](https://exhibits.library.cornell.edu/vintage-vision/feature/george-barbier)

![image](https://user-images.githubusercontent.com/6855473/122925765-26a4e400-d335-11eb-82a3-22c90d67ca0f.png)

### 3.x

When hovering over a Browse image in the 3.x site, the title and metadata are display over the image.

Example: Vintage Vision -> Artists -> [George Barbier](https://exhibits-integration.xcvhmd2mim.us-east-1.elasticbeanstalk.com/vintage-vision/feature/george-barbier)

![image](https://user-images.githubusercontent.com/6855473/122926065-7be0f580-d335-11eb-92c2-fcddb1c5e82d.png)

Questions:
* should it just display title or should it include metadata (need to investigate to determine how to limit display to just title)
* if metadata is included, what metadata should be included (not sure how easy this is to control)
* should the display be restyled

**Comment by mhk33** [comment]
IMO, the full metadata display seems like too much info to me and not very legible/usable anyway. I suspect the color contrast for the text on the opaque background on top of the image may not be fully accessible anyway (depending on the image used). I think prefer it with just the title.

**Comment by elrayle** [comment]
Only showing the title and basic styling of overlay is fixed in commit https://github.com/cul-it/exhibits-library-cornell-edu/pull/469/commits/ff376e21b69d502eaa6be2c359f50c6ee49f92a3

@mhk33 May want to do additional styling on the overlay.
