### ISSUE TITLE
3.0 Validation: exhibit text is double-spaced

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#501]
2021-08-11 email from Karl Rozyn:

> Three pages in [Apples to Cider](https://exhibits-prod-1.library.cornell.edu/cider) have become weirdly double-spaced (home page, Bitter is Better, Harvest to Bottle).  The same text spacing issue exists in [Unturned Leaves](https://exhibits-prod-1.library.cornell.edu/unturned-leaves) (pages home, MF Lewis. Sarah Price. Mary Elizabeth Banning) and [Story/Lines](https://exhibits-prod-1.library.cornell.edu/story-lines) (just the home page).

**Comment by mhk33** [comment]
It looks like extra <p> tags have been added to these pages. If you go into Edit mode the widgets look as they should.

**Comment by elrayle** [comment]
I fixed the pages that were specifically mentioned in this issue.  

### Spotlight 2.x handling of text widget

Apparently Spotlight 2.x was ok with a paragraph widget having line returns in the text.  They were ignored which meant that the text within a single widget displayed as a paragraph.

This means that a page with 3 paragraphs would require 3 text widgets.

### Spotlight 3.x handling of text widget

In Spotlight 3.x, a line return within the contents of a text widget is treated as a line return.  This means that some exhibits need to be edited to remove line returns in places where they are not wanted.

This also means that a single text widget can be used for multiple paragraphs by including a line return between paragraphs.

**Comment by elrayle** [comment]
Closing because this is not a technical issue.  It can only be fixed by editing content.  Exhibit creators will be notified of this change in behavior.
