### ISSUE TITLE
3.0 Validation: image uploads for horizontal rows limited to 1Mb

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#504]
2021-07-30 email from Craig Mains...

>  Image uploads for horizontal rows are limited to 1meg but load page doesn’t say there’s a limit.  (I like the added link option here!) 

Should we...
* add text indicating the limit
* adjust the limit

**Comment by JesiBuell79** [comment]
@chrisrlc was this already fixed?

**Comment by chrisrlc** [comment]
Tested on exhibits-int and seems to be fixed now. This may have gotten fixed when we fixed the missing nginx configs with the client_max_body_size setting 2 weeks ago.
