### ISSUE TITLE
3.0 Validation: broken item links

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#505]
2021-07-30 email from Craig Mains...

> Some of the item links in my unpublished “Bluest Eye” exhibit were broken.  Images on Lorain County, three in a row.  (would be nice if you could sort by title when going through exhibit items) . Site gave me an error while trying to look through my items here.

**Comment by elrayle** [comment]
I wasn't able to reproduce.  Requested more information from Craig Mains because it is not clear that I was testing the links that were causing the error.

**Comment by chrisrlc** [comment]
Can't reproduce and no updates since last April after reaching out to reporter. Closing out but can reopen if new report comes in.
