### ISSUE TITLE
3.0 Validations: headings are the same size

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#507]
### Description

Reported by Susette Newberry in 2021-08-18 email...

>  The issues that I am having are that the styles for quotations (thank you for adding that to the github issue tracker) and headings look absolutely awful. For headings, see: https://exhibits-prod-1.library.cornell.edu/uris-historical-tour/about/resources vs. https://exhibits.library.cornell.edu/uris-historical-tour/about/resources (it doesn’t seem visually hierarchical). 

### Expected (current production)

_NOTE: In the example, Resources is `<h1>` and Primary Sources is `<h2>`.

![image](https://user-images.githubusercontent.com/6855473/129934498-0b0804f9-cfc9-4b8e-b5b7-0090087dfb09.png)

### Actual (3.0 site)

_NOTE: In the example, Resources is `<h1>` and Primary Sources is `<h2>`.

![image](https://user-images.githubusercontent.com/6855473/129934284-4b0a67c6-bd0a-4121-8e78-2f2e69edeae1.png)

**Comment by elrayle** [comment]
@mhk33 Do you have thoughts on this issue?  Seems like it might be a simple css change.

**Comment by mhk33** [comment]
I will take a look. I'm thinking if I remove any heading font size rules from the previous design's scss that should reset things to the default spotlight font sizes and perhaps things will look a bit better. Also thinking about Craig's UI feedback on font sizes in other areas.

**Comment by mhk33** [comment]
I changed the default body font to Freight Sans Pro (the official Cornell font) so it is now used site-wide and there is slightly more differentiation between font sizes now.
