### ISSUE TITLE
3.0 Validations: get message "change you wanted was rejected" when trying to view image

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#510]
### Description

Reported by Craig Main in 2021-08-20 email...

> This came up when clicking on any image in "Selections from the Barazangi Map Collection" when using the test link from your email via my iPhone.  Not logged in as administrator ( I think). Page opened automatically in Safari. No issue like this when pasting link in Chrome or Firefox on iPhone. Then Safari was fine too. 

### Expected

Current Production: [Tectonic Units of the Middle East](https://exhibits.library.cornell.edu/barazangi-map-collection/catalog/60-2789)

![image](https://user-images.githubusercontent.com/6855473/133838209-5b9324be-955b-45ff-b68b-f01501dba46b.png)

NOTE: When clicking the image from the parent page, the URL is generated as: https://exhibits.library.cornell.edu/barazangi-map-collection/catalog/60-2789

### Actual

3.0 Upgrade: [Geological map of Syria](https://exhibits-prod-1.library.cornell.edu/catalog/60-2789/track?counter=-1&document_id=60-2789&search_id=7075945)

<img src="https://user-images.githubusercontent.com/6855473/133839774-1ed83f54-085b-4f70-bc60-4e01995db174.png" width="300">

NOTE: When clicking the image from the parent page, the URL is generated as: https://exhibits-prod-1.library.cornell.edu/catalog/60-2789/track?counter=-1&document_id=60-2789&search_id=7075945

If you remove everything from `/track?` to the end, the page will display without the error.  https://exhibits-prod-1.library.cornell.edu/catalog/60-2789

### Steps to Reproduce

Tested in Chrome on Mac

* go to page [Geology Features](https://exhibits-prod-1.library.cornell.edu/barazangi-map-collection/feature/geology-features)
* click on the first map at the top right of the page, labeled "Tectonic Units of the Middle East"

Change Rejected error message is displayed instead of the image.

**Comment by chrisrlc** [comment]
Not able to reproduce. Also sounds like this may have been related to some testing from over a year ago. Can reopen if new reports come in.
