### ISSUE TITLE
3.0 Validation: UI recommendations related to appearance of exhibit title/subtitle/headers

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#542]
Reported by Craig Main in 2021-08-20 email...

- [x] ONLINE EXHIBITIONS grey banner adds clutter and competes with title of exhibit. I believe the previous header looked better.  
    * _RESPONSE: (by mhk33) - This is the direction we have received and has been approved by Library Communications and Central Branding, we likely need to work with what we have here._
- [x] Exhibit Main Titles in all caps are difficult to read.  
    * _RESPONSE: (by mhk33) - Agreed, will change and bump up font size_
- [x] Main exhibit title and subtitle could be closer together and dropped lower to the shaded area of the banner. 
    * _RESPONSE: (by mhk33) - Will review the font size and positioning._
- [x] The secondary title text is now easier to read as it is all white. Maybe switch style to all white main title and drop shadow subtitle smaller font. 
    * _RESPONSE: (by mhk33) - Will review font size and positioning in relation to each other._
- [x] General header titles increased in size. Headers are larger than exhibit title and seem too big for the page. They seem too big on cell phone view as well. 
    * _RESPONSE: (by mhk33) -  Will take a look._

**Comment by mhk33** [comment]
I think these are all generally a bit better. Maybe not perfect, but I hesitate to override the default heading styles; it can become unwieldy and difficult to know how those overrides effect everything in the system. We can create new issues if there is something major needs improvement.
