### ISSUE TITLE
3.0 Validation: Image record pages loading awkward composition

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#544]
Reported by Craig Main in 2021-08-20 email...

> Image record pages loading awkward composition.  Image size increase is better, but text should line up to the left of image or directly below with image more centered. (if +/- controls were at the bottom, the image and text could be justified at the top. )  

### Expected (from 2.x Spotlight)

Page: https://exhibits.library.cornell.edu/cider/feature/bitter-is-better-cider-apples

![image](https://user-images.githubusercontent.com/6855473/165499981-5f6fbda0-ddb2-4d62-b141-83fcde917f6d.png)

### Actual (from 3.x Spotlight)

Page: https://exhibits-prod-1.library.cornell.edu/cider/feature/bitter-is-better-cider-apples

![image](https://user-images.githubusercontent.com/6855473/165500158-a8e2d3e1-29fd-47a3-a39e-379ca968c742.png)

**Comment by mhk33** [comment]
I added a class to the solr documents embed sir trevor block, so that I could target that element. I added some padding so that the text aligns with the top of the embedded image. I checked a few pages and it seems to be looking good.
