### ISSUE TITLE
Image display in masthead not working correctly

### ISSUE THREAD

**Issue by hudajkhan** [cul-it/exhibits-library-cornell-edu#577]
### Describe the bug
There are two issues with Spotlight in the Challenging the Deep exhibit (https://exhibits.library.cornell.edu/challenging-the-deep).  First, the masthead will not display the image selected for it (which is in the exhibit items).   

### To Reproduce
1.

**Comment by hudajkhan** [comment]
Selecting the checkbox on the image upload page enables the image to be shown in the masthead

**Comment by chrisrlc** [comment]
Can't reproduce. Masthead image displays fine when checking the "Show background image in masthead" checkbox, and the original exhibit that reported the issue is correctly displaying a masthead image. Can reopen if newer reports come in.
