### ISSUE TITLE
Review permissions scheme

### ISSUE THREAD

**Issue by starsplatter** [cul-it/exhibits-library-cornell-edu#59]
Right now curators can do a limited set of tasks. I made Hannah an admin so she could name and configure her site.

Can we review what curators vs admins can do? And also how easy/difficult it is to config this in our local app?

**Comment by cappadona** [comment]
Details on roles and permissions are intertwined on the [configuration settings](https://github.com/projectblacklight/spotlight/wiki/Configuration-settings) page from Spotlight wiki.

**Comment by starsplatter** [comment]
One question I have is whether we want people to be able to create exhibits on demand. If so, then the site admin tasks would need to be given to curators. If not, then we'll need to set up a request process (which might be something simple, a form on the main site? a lib guide for spotlight exhibits with the form?)

**Comment by cappadona** [comment]
For short term, stick with existing limitations of roles in Spotlight, and create an onboarding form.
