### ISSUE TITLE
[BUG] Dashboard analytics show no data

### ISSUE THREAD

**Issue by chrisrlc** [cul-it/exhibits-library-cornell-edu#601]
### Describe the bug
https://exhibits.library.cornell.edu/dashboard

"No data" displaying from the embedded Looker Studio report: https://lookerstudio.google.com/embed/reporting/c5490b84-9d13-45bc-82a5-64a0da98bbb3/page/glhpB

Adjusting the time frame to all of last year shows that data dropped off in May 2022.

**Comment by chrisrlc** [comment]
The dashboard was using the wrong GA property id (the one for int instead of prod). Just updated this and the correct GA account seems to be tracking real time data now. I'll check again tomorrow to confirm that the dashboard is populating again. This fix will not retroactively populate the missing data from May 2022-now.

We'll still need to update permissions and documentation based on this outage. But I've got a running list of TODOs in our Confluence.

**Comment by mhk33** [comment]
Nice job!
