### ISSUE TITLE
importing h's test exhibit is failing with duplicate entry error

### ISSUE THREAD

**Issue by starsplatter** [cul-it/exhibits-library-cornell-edu#68]
ActiveRecord::RecordNotUnique (Mysql2::Error: Duplicate entry '-gbBxeN5gY-YGmMDoYZj' for key 'index_spotlight_contact_emails_on_confirmation_token': INSERT INTO `spotlight_contact_emails` (`exhibit_id`, `email`, `confirmation_token`, `confirmation_sent_at`, `created_at`, `updated_at`) VALUES (8, '[H'S EMAIL]', '-gbBxeN5gY-YGmMDoYZj', '2017-03-20 16:28:37', '2017-03-20 16:28:37', '2017-03-20 16:28:37')):

**Comment by starsplatter** [comment]
H entered her email as a contact for the exhibit, but she already existed as an admin on the site. The duplication of her email address caused the error. Should report on the spotlight repo.

**Comment by starsplatter** [comment]
I think this might actually have been because her email hadn't been confirmed yet at the time of export. Not sure yet.

**Comment by cappadona** [comment]
We're going with Jenn's suspicion for now. Will reopen if it returns in the future.
