### ISSUE TITLE
the number of categories that can be included in browse categories is limited by the css but the limitation is not reflected in the curator UI

### ISSUE THREAD

**Issue by starsplatter** [cul-it/exhibits-library-cornell-edu#70]
I'll report this on the main project as well.

**Comment by starsplatter** [comment]
https://github.com/projectblacklight/spotlight/issues/1761

**Comment by starsplatter** [comment]
https://github.com/projectblacklight/spotlight/blob/master/app/assets/stylesheets/spotlight/_featured_browse_categories_block.scss

**Comment by cappadona** [comment]
For now, we will handle this with local documentation.

**Comment by mhk33** [comment]
This has been added to the documentation under Editing Pages >Exhibit item widgets:
https://cul-it.github.io/exhibits-library-cornell-edu/
