### ISSUE TITLE
As a curator I want to be able to do as much with my feature pages as i can with my items, because the feature pages are what make it an "exhibit" and not a catalog.

### ISSUE THREAD

**Issue by starsplatter** [cul-it/exhibits-library-cornell-edu#73]

**Comment by starsplatter** [comment]
"You can do a lot with items but not as much with feature pages."
"Would like to have all the functionality of items for the feature pages so you could have a carousel of feature pages on the home page"
"It would be good to be able to put text next to a carousel of feature pages"
"Search should also search the feature pages"

**Comment by JesiBuell79** [comment]
Closing as I'll add these to the usability ticket
