### ISSUE TITLE
Create onboarding form

### ISSUE THREAD

**Issue by cappadona** [cul-it/exhibits-library-cornell-edu#77]
Jenn suggests reviewing Stanford's onboarding policy.

**Comment by mhk33** [comment]
What would we want on an onboarding form?
* Contact info
* Exhibit title
* Exhibit description

Anything else?

And put this form behind CUWebAuth. Jenn and I discussed linking to it from the main site's Online Exhibits page as well as our documentation site.

**Comment by mhk33** [comment]
Here's a basic form:
https://www.library.cornell.edu/about/collections/online-exhibitions/request

Perhaps we want a little descriptive information at the top? What it is for, mention of Spotlight, perhaps? And a link to the site.

**Comment by cappadona** [comment]
I think this looks good and agree a quick description including a link to the [exhibits site](https://exhibits.library.cornell.edu) would be helpful. Thanks.

**Comment by mhk33** [comment]
I updated the wording on the Online Exhibitions page and added some intro text above the in-take form.
https://www.library.cornell.edu/about/collections/online-exhibitions
https://www.library.cornell.edu/about/collections/online-exhibitions/request

I think this is all set and we can start pointing people to this form.
