### ISSUE TITLE
Cannot edit home page after adding browse categories widget

### ISSUE THREAD

**Issue by ker87** [cul-it/exhibits-library-cornell-edu#88]
Added a browse categories widget, edit button now returns the error/check logs page.

**Comment by mhk33** [comment]
I enabled "browse" on Jenn's test exhibit and then tried to edit the home page to add browse categories, but received a "we're sorry, something went wrong" message when I clicked the Edit button.

**Comment by cappadona** [comment]
Thanks Melissa...identical to what we're experiencing in the Vintage Vision exhibit as well.

**Comment by starsplatter** [comment]
I suspect this is related to the ordering of the engines which hasn't been deployed out yet, let me look locally and then we'll see if we can push that through the process.

Browses are "saved searches" so if search saving, history, etc aren't working it might be manifesting here.

**Comment by mhk33** [comment]
I was able to add the widget on fine on exhibits-dev.

**Comment by cappadona** [comment]
https://github.com/projectblacklight/spotlight/issues/1782

**Comment by cappadona** [comment]
Following @jkeck's lead in sul-dlss/exhibits#475, I manually removed the following trailing object from the `content` field for the exhibit's home page and two feature pages as well (*George Lepape* & *AE Marty*):

```json
{
  "type": "featured_pages",
  "data": {}
}
```

@ker87 You should be all set!
