### ISSUE TITLE
Directory updates for deployment

### ISSUE THREAD

**Issue by starsplatter** [cul-it/exhibits-library-cornell-edu#97]
from alan:
we’ll also need to let jenkins own the /cul/web/exhibits-dev.library.cornell.edu/rails-app directory

[2:07] 
and update the DocumentRoot in vhost-local.conf to be /cul/web/exhibits-dev.library.cornell.edu/rails-app/current/public

**Comment by cappadona** [comment]
@starsplatter Should be all set. Apache will need to be restarted for the update to `DocumenRoot` directive to go into effect.

**Comment by cappadona** [comment]
Ended up reverting this due to waiting on an upstream fix from CIT related to #95. Moving back to in progress.

**Comment by elrayle** [comment]
We deploy to Elastic Beanstalk using Jenkins. This no longer applies.
